# Vulture whitelist for false positives

# Pydantic settings fields are used by the framework automatically
model_config
memgraph_uri
redis_uri
redis_ttl
embedding_model
emotional_embedding_model
core_identity_node
alpha_snooze_enabled
alpha_snooze_ollama_host
alpha_snooze_ollama_port
alpha_snooze_model
alpha_snooze_time_window
alpha_snooze_timeout
reminiscer_enabled
reminiscer_ollama_host
reminiscer_ollama_port
reminiscer_model

# Pydantic field validators are used by the framework
validate_log_level
cls