volumes:
  alpha-recall-venv:

services:
  # memgraph:
  #   image: memgraph/memgraph-mage:latest
  #   container_name: memgraph
  #   ports:
  #     - "7687:7687"  # bolt://localhost:7687
  #   command: ["--log-level=TRACE"]
  #   volumes:
  #     - ../../Alpha-Recall-Volumes/memgraph:/var/lib/memgraph

  # memgraph-lab:
  #   image: memgraph/lab:latest
  #   container_name: memgraph-lab
  #   ports:
  #     - "6002:3000"  # http://localhost:6002
  #   depends_on:
  #     - memgraph
  #   environment:
  #     - QUICK_CONNECT_MG_HOST=memgraph
  #     - QUICK_CONNECT_MG_PORT=7687

  # redis:
  #   image: redis:latest
  #   container_name: redis
  #   ports:
  #     - "6379:6379"  # redis://localhost:6379
  #   volumes:
  #     - ../../Alpha-Recall-Volumes/redis:/data

  alpha-recall-1:
    build:
      dockerfile: Dockerfile
      target: dev
    container_name: alpha-recall-1
    ports:
      - "127.0.0.1:19005:9005"  # Only bind to localhost for security
    # depends_on:
    #   - memgraph
    #   - redis
    environment:
      - FASTMCP_LOG_LEVEL=DEBUG
      - LOG_LEVEL=DEBUG
      - LOG_FORMAT=rich
      - MEMGRAPH_URI=bolt://host.docker.internal:7687
      - REDIS_URI=redis://host.docker.internal:6379/0
      - REDIS_TTL=2000000 # 2 megaseconds
      - EMBEDDING_MODEL=sentence-transformers/all-mpnet-base-v2
      - EMOTIONAL_EMBEDDING_MODEL=ng3owb/sentiment-embedding-model
      - CORE_IDENTITY_NODE=Alpha Core Identity
      - MCP_TRANSPORT=streamable-http
      - HOST=0.0.0.0
      - PORT=9005
      # - FASTMCP_HOST=0.0.0.0
      # - FASTMCP_PORT=9005
      - PYTHONUNBUFFERED=1
      # Alpha-Snooze Configuration
      - ALPHA_SNOOZE_ENABLED=true
      - ALPHA_SNOOZE_OLLAMA_HOST=host.docker.internal
      - ALPHA_SNOOZE_OLLAMA_PORT=11434
      - ALPHA_SNOOZE_MODEL=qwen2.5:3b
      - ALPHA_SNOOZE_TIME_WINDOW=24h
      - ALPHA_SNOOZE_TIMEOUT=60
      # Alpha-Reminiscer Configuration
      - REMINISCER_ENABLED=true
      - REMINISCER_OLLAMA_HOST=host.docker.internal
      - REMINISCER_MODEL=qwen2.5:7b
    volumes:
      - ./src:/app/src
      - ./huggingface-cache:/root/.cache/huggingface
      - alpha-recall-venv:/app/.venv  # Preserve virtual environment
    command: ["uv", "run", "python", "-m", "alpha_recall"]
