volumes:
  alpha-recall-venv:
  alpha-recall-uv-cache:
  memgraph-dev-data:
  redis-dev-data:

services:
  memgraph:
    image: memgraph/memgraph-mage:latest
    container_name: memgraph-dev
    ports:
      - "7687:7687"  # bolt://localhost:7687
    command: ["--log-level=TRACE"]
    volumes:
      - memgraph-dev-data:/var/lib/memgraph

  redis:
    image: redis:latest
    container_name: redis-dev
    ports:
      - "6379:6379"  # redis://localhost:6379
    volumes:
      - redis-dev-data:/data

  alpha-recall-1:
    build:
      dockerfile: Dockerfile
      target: dev
    container_name: alpha-recall-1
    ports:
      - "127.0.0.1:${ALPHA_RECALL_DEV_PORT:-19005}:8000"  # Only bind to localhost for security
    depends_on:
      - memgraph
      - redis
    environment:
      - FASTMCP_LOG_LEVEL=DEBUG
      - LOG_LEVEL=DEBUG
      - LOG_FORMAT=rich
      - MEMGRAPH_URI=bolt://memgraph:7687
      - REDIS_URI=redis://redis:6379/0
      - REDIS_TTL=2000000 # 2 megaseconds
      - EMBEDDING_MODEL=sentence-transformers/all-mpnet-base-v2
      - EMOTIONAL_EMBEDDING_MODEL=ng3owb/sentiment-embedding-model
      - CORE_IDENTITY_NODE=Alpha Core Identity
      - MCP_TRANSPORT=streamable-http
      - HOST=0.0.0.0
      - PORT=8000
      - PYTHONUNBUFFERED=1
      # Alpha-Snooze Configuration
      - ALPHA_SNOOZE_ENABLED=true
      - ALPHA_SNOOZE_OLLAMA_HOST=host.docker.internal
      - ALPHA_SNOOZE_OLLAMA_PORT=11434
      - ALPHA_SNOOZE_MODEL=qwen2.5:3b
      - ALPHA_SNOOZE_TIME_WINDOW=24h
      - ALPHA_SNOOZE_TIMEOUT=60
      # Alpha-Reminiscer Configuration
      - REMINISCER_ENABLED=true
      - REMINISCER_OLLAMA_HOST=host.docker.internal
      - REMINISCER_MODEL=qwen2.5:7b
    volumes:
      - ./src:/app/src
      - ./huggingface-cache:/root/.cache/huggingface
      - alpha-recall-venv:/app/.venv  # Preserve virtual environment
      - alpha-recall-uv-cache:/root/.cache/uv  # Preserve uv download cache
    command: ["uv", "run", "python", "-m", "alpha_recall"]
